Develop
newyee/js-kadai4 pull request #1
Opened 2021-01-13 15:41 UTC by newyee

ご確認、よろしくお願いします。

2021-01-15 02:00 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。
また、課題の【学習できる内容】に「クラス（オブジェクト指向）」とあるように、クラスを使用した実装ができると良いのですがいかがでしょうか？
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Classes

2021-01-15 02:00 UTC, kouki-iwahara commented on js/kadai.js
> +  const startQuiz = async () => {
この関数で行っている処理を、もう少し目的ごとに別の関数に切り分けても良いかなと思います。

2021-01-15 02:00 UTC, kouki-iwahara commented on js/kadai.js
> +      let br = document.createElement('br')
改行はcssかブロック要素を利用して行うと良いでしょう。

2021-01-15 02:00 UTC, kouki-iwahara commented on js/kadai.js
> +            location.reload();
ここもDOMを書き換えることで初期画面に戻せればSPAとしても良いのですが、いかがでしょうか？
が、修正はお任せします。

2021-01-15 02:00 UTC, kouki-iwahara commented on js/kadai.js
> +  let responsData = {}
constで定義するためにも、letで予め定義しておく必要はないかなと思います。
関数の中で定義すればスコープも狭められますね。

2021-01-25 13:42 UTC, myzktkyk requested changes
何点かコメントをしております。

2021-01-25 13:42 UTC, myzktkyk commented on js/kadai.js
> +    const quizData = [quiz_one,quiz_two,quiz_three,quiz_four,quiz_five,quiz_six,quiz_seven,quiz_eight,quiz_nine,quiz_ten]
ちょっと冗長に思えました。
以下のようにすれば `forEach` を使った繰り返しに書き換えられます。

```suggestion
    const quizData = [];
    results.forEach((result) => {
      quizData.push(new Quiz(result.category, result.difficulty, result.question, result.correct_answer, result.incorrect_answers));
    });
```

2021-01-25 13:42 UTC, myzktkyk commented on js/kadai.js
> +    startQuiz(quizData)
`startQuiz` は `async` なので呼び出すときは `await` を使うべきです。
```suggestion
    await startQuiz(quizData)
```

2021-01-25 13:42 UTC, myzktkyk commented on js/kadai.js
> +    const data = await respons.json();
Api 呼び出しをするところは `try/catch` を利用することを心掛けてください。
Api はネットワークエラーなど予期しないエラーが発生しやすいです。

```suggestion
    try {
      const respons = await fetch('https://opentdb.com/api.php?amount=10')
      const data = await respons.json();
      return data;
    } catch (e) {
      console.error(e)
    }
```

2021-01-27 13:51 UTC, myzktkyk approved these changes
1点だけ指摘をしております…。

2021-01-27 13:51 UTC, myzktkyk commented on js/kadai.js
> +      results[9].incorrect_answers);
この部分がそのままなのはまずいのではないでしょうか…？
次の行以降の処理があれば、これらは不要になるはずです。

2021-02-03 10:49 UTC, merged